version: "3.9"

x-common-variables: &common-variables
  TOKEN_SECRET: a8db712c5129e52c669d8599d982f071569b425519c638dcfd4ea87f8ba769232336cda2ee4bcd5d13f77b7cfb8d73d01ba0
  # COOKIE_SECRET: dette_er_min_lange_hemmelighet
  DEBUG: 1
  # EMAIL SETTINGS
  # MAIL_USERNAME: test
  # MAIL_PASSWORD: test
  # MAIL_FROM: test
  # MAIL_PORT: test
  # MAIL_SERVER: test
  # MAIL_TLS: test
  # MAIL_SSL: test
  # USE_CREDENTIALS: test


services:
  # FASTAPI BACKEND
  backend:
    container_name: sworkout-fastapi-backend
    build: ./backend
    working_dir: /code
    command: uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    environment:
      FASTAPI_PROJECT_NAME: ${FASTAPI_PROJECT_NAME}
      FASTAPI_PROJECT_VERSION: ${FASTAPI_PROJECT_VERSION}
      FASTAPI_DESCRIPTION: ${FASTAPI_DESCRIPTION}
      FASTAPI_PROJECT_STATUS: ${FASTAPI_PROJECT_STATUS}
      FASTAPI_AUTHENTICATION_SECRET_KEY: ${FASTAPI_AUTHENTICATION_SECRET_KEY}
      FASTAPI_AUTHENTICATION_ALGORITHM: ${FASTAPI_AUTHENTICATION_ALGORITHM}
      FASTAPI_AUTHENTICATION_TOKEN_EXPIRE_MINUTES: ${FASTAPI_AUTHENTICATION_TOKEN_EXPIRE_MINUTES}
      FASTAPI_RECOVERY_KEY_EXPIRE_MINUTES : ${FASTAPI_RECOVERY_KEY_EXPIRE_MINUTES}
      FASTAPI_RECOVERY_SECRET_KEY: ${FASTAPI_RECOVERY_SECRET_KEY}
      FASTAPI_RECOVERY_LENGTH: ${FASTAPI_RECOVERY_LENGTH}
      FASTAPI_MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      FASTAPI_MYSQL_USER: ${MYSQL_USER}
      FASTAPI_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      FASTAPI_MYSQL_DATABASE: ${MYSQL_DATABASE}
      FASTAPI_MYSQL_HOST: ${MYSQL_HOST}
      FASTAPI_DOCS_URL: ${FASTAPI_DOCS_URL}
      FASTAPI_DOCKER: ${FASTAPI_DOCKER}
    volumes:
      - ./backend:/code
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
      # - "HOST:CONTAINER"
    restart: on-failure
  # db
  mysql:
    container_name: sworkout-mysql-db
    build: ./database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
  # adminer
  adminer:
    container_name: sworkout-adminer-database_manager
    depends_on:
      - mysql
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
  # frontend:
  #   container_name: sworkout-frontend
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   volumes:
  #      - ./frontend:/usr/src/app/frontend
  #      - /usr/src/app/frontend/node_modules

