import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Button from '../components/Button'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <main className="">
        <section className="bg-hero-image bg-white bg-center bg-cover py-32 ">
          <div className="container mx-auto px-4">
            <h1 className="text-4xl leading-normal text-primary-color lg:leading-normal lg:text-4xl font-bold">
              Gjør treningen din <span className='text-6xl'>MER</span> <br/>
              spennende
            </h1>
            <h2 className="text-2xl text-white leading-loose lg:leading-loose lg:text-3xl">
              Ved å logføre aktiviteten!
            </h2>

            <p className='pb-12'>Start registreringen i dag, og nå dine drømmer!</p>

            <Link href="/authentication/register">
              <a className="">
                <Button className={"border bg-primary-color text-secondary-color hover:text-secondary-color-hover"}>
                  Register deg!
                </Button>
              </a>
            </Link>

          </div>
        </section>
      </main>

      <Footer/>
    </>
  )
}
